# Generated by Django 5.1.3 on 2024-11-24 15:00

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('dept', models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT')], default='', max_length=120, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=12, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('passout_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('event_ids', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('student', 'Student'), ('alumni', 'Alumni')], default='student', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('work_location', models.CharField(max_length=200)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT')], default='NONE', max_length=120, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=12, null=True)),
                ('cgpa', models.FloatField(blank=True, default=0.0)),
                ('passout_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('current_job', models.CharField(blank=True, max_length=200, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT')], default='NONE', max_length=120, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=12, null=True)),
                ('cgpa', models.FloatField(blank=True, default=0.0)),
                ('passout_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
