# Generated by Django 5.1.2 on 2024-10-29 17:53

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('dept', models.CharField(choices=[('', ''), ('COMPUTER SCIENCE AND ENGINEERING', 'COMPUTER SCIENCE AND ENGINEERING'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ELECTRONICS AND COMMUNICATION ENGINEERING', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('ELECTRICAL AND ELECTRONIC ENGINEERING', 'ELECTRICAL AND ELECTRONIC ENGINEERING'), ('MECHANICAL ENGINEERING', 'MECHANICAL ENGINEERING'), ('CIVIL ENGINEERING', 'CIVIL ENGINEERING')], default='', max_length=120, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=12, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('passout_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('event_ids', models.TextField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
