# Generated by Django 5.1.4 on 2024-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alumni_cv_student_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='dept',
            field=models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT'), ('ECON', 'ECONOMICS')], default='NONE', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT'), ('ECON', 'ECONOMICS')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT'), ('ECON', 'ECONOMICS')], default='NONE', max_length=120, null=True),
        ),
    ]
