# Generated by Django 5.1.2 on 2024-11-18 17:30

import django.core.validators
import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT')], default='', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('work_location', models.CharField(max_length=200)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('NONE', ''), ('MM', 'MANAGEMENT AND MARKETING'), ('MIS', 'MANAGEMENT AND INFORMATION SYSTEM'), ('FFI', 'FINANCE AND FINANCIAL INSTITUTIONS'), ('GA', 'GENERAL ADMINISTRATION'), ('AC', 'ACCOUNTING'), ('OM', 'OPERATIONS MANAGEMENT')], default='NONE', max_length=120, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=12, null=True)),
                ('passout_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
