# Generated by Django 5.1.4 on 2024-12-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_alumni_dept_alter_profile_dept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='registration_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='id_number',
        ),
    ]
