# Generated by Django 5.1.2 on 2024-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_role_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='cgpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
